version: "2"

services:

  reactnative:
    build:
      context: .
      dockerfile: dockerfile
    container_name: reactnative
    network_mode: "host"
    user: "root"
    volumes:
      - ./:/home/node/reac-native
    expose:
      - "3001"
    command: "stf local --public-ip 192.168.0.115"
    environment:
      - COMPOSE_PROJECT_NAME
    tty: true